### ISSUE TITLE
Does it support Raspberry Pi B?

### ISSUE THREAD

**Issue by Coro365** [ts1/PiIR#3]
When I ran PiIR on a Raspberry Pi Model B Rev 2, `piir record` worked and generated exactly the same light.json as in README.md, but when I played it, the IR LED lit up, but I could not control the appliances.
`piir play -g 17 -f light.json off`
Does PiIR only work with pi zero as suggested in #1 ?

Thank you very much!

```
Model: Raspberry Pi Model B Rev 2 (manufactured in 2011)
OS: Raspbian GNU/Linux 10 (buster)
PiIR version: 0.2.5

Transistor: 2SC1815 (used in LIRC)
IRLED: I don't know the model number, but it's the one we used in LIRC.
R1: 470Ω
R2: 10KΩ
```

**Comment by ts1** [comment]
Does [irrp.py](http://abyz.me.uk/rpi/pigpio/examples.html#Python_irrp_py) work on your hardware?
If it does, PiIR should work.

**Comment by Coro365** [comment]
Sorry for the late reply.
I tried PiiR and irrp.py with Pi1 and Pi3 respectively, but no improvement.
So I bought a new RaspberryPi4 and inserted the SD card that I was using in the Pi3 and experimented with it, and was able to control the appliances.
After that, I put the SD card back in the Pi3 and tested it again, but I couldn't control the appliances.
I don't know why it doesn't work with Pi1 and Pi3 but works with Pi4, but thank you very much.
